### ISSUE TITLE
Question regarding how Optional<T>.Map handles values types return from mapping function

### ISSUE THREAD

**Issue by Porl91** [ProductiveRage/Bridge.Immutable#10]
This question relates to the following line:
https://github.com/ProductiveRage/Bridge.Immutable/blob/master/ProductiveRage.Immutable/Optional.cs#L64

If the result of the mapped value is null then the result of the Map method is Optional<TResult>.Missing.
This only works with reference types, so does it makes sense to change this to default(TResult) so it can work as expected with value types?

**Comment by ProductiveRage** [comment]
That would prevent you from returning zero in a Map call where the destination type was int because default(int) is zero. The same sort of thing happens with bool and with structs (the default value for a struct is one where all of its fields have default values and this may be a valid value that should not be interpreted as Missing).

I think that the only way to make Map do what you want would be for an additional method overload to be added to the library:

`public Optional<TResult> Map<TResult>(Func<T, Optional<TResult>> mapper)`

.. but I *think* that would prevent the C# compiler from inferring the type of TResult and I'm pretty sure that it would introduce breaking changes because the compiler would not know how to determine which overload should be called from existing code that uses a lambda.

In your case, I guess  that you will have to write your code in the style of

```
var newOptionalValue = (oldOptionalValue.IsDefined && SomeCondition)
    ? TranslateValue(oldOptionalValue.Value)
    : Optional<NewType>.Missing;
```
