### ISSUE TITLE
Analyser mis-identifies IAmImmutable Instances and generates warnings when there is a simple compile error

### ISSUE THREAD

**Issue by calcock** [ProductiveRage/Bridge.Immutable#2]
A simple compile error in one class (in this case something which has not been updated to use the optional type's value property) causes lots of classes to be mis-reported as being incorrect IAmImmutable implementations when they don't inherit from the interface
![7916fa99-266a-4ee7-845c-35dbf2b26c36](https://cloud.githubusercontent.com/assets/574233/17144686/82a6b776-534f-11e6-986d-0f53f76b4375.png)

**Comment by ProductiveRage** [comment]
I've fixed an issue where the warning that you are seeing was reported on types that had mutable fields, even if they didn't implement IAmImmutable. That problem did not require a compile error, though - so, while I suspect that it's the same as you have reported here, I'm not 100% sure. I've pushed the update to NuGet (1.8.4), will you give it a go when you get a chance and see if your problems go away?

**Comment by calcock** [comment]
I've just updated to 1.8.4, I no longer get them as errors, but I do see lots of warnings 
'IAmImmutable implementations may not have non-readonly public fields (such as RequestId)' on classes which are not marked with the 'IAmImmutable' marker interface

**Comment by ProductiveRage** [comment]
I'm afraid that I can't reproduce this! Any chance you can share a full sample or repo illustrating the problem somewhere?

To try my best, I created a new project and added Bridge (1.14.0), Bridge.React (1.7.0), ProductiveRage.Immutable (1.8.4) and ProductiveRage.Immutable.Extensions (1.2.1) and then populated Class1.cs with the following to reproduce the "cannot convert from 'ProductiveRage.Immutable.Optional<string>' to 'string'" that you have -

```
using Bridge.Html5;
using Bridge.React;
using ProductiveRage.Immutable;

namespace BridgeReactIssue1_Test
{
	public class Class1
	{
		[Ready]
		public static void Main()
		{
			Write(Optional.For("xyz")); // Compile error
		}

		public static void Write(string value)
		{
		}
	}

	public class DataUpdated<T> : IDispatcherAction
	{
		public RequestId RequestId;
		public T Data;
	}

	public static class DataUpdated
	{
		public static DataUpdated<T> For<T>(RequestId requestId, T data)
		{
			return new DataUpdated<T> { RequestId = requestId, Data = data };
		}
	}
}
```

I only see that single expected error, I don't get all of the other IAmImmutable-related issue (mis)reported.

Often, when updating NuGet packages with analysers, you need to restart Visual Studio - this will usually appear as a warning in the Error List. However, since the errors changed from Error to Warning after you updated ProductiveRage.Immutable, this doesn't sound like it's the cause of the problems.

(Note: I only added ProductiveRage.Immutable.Extensions since it includes the RequestId class, which allowed me to write code that was closer to that which you included in the screenshot).

**Comment by calcock** [comment]
I've just re-opened the solution which was causing issues today, and with no changes it is no longer exhibiting the issue - I wonder if the warnings were stuck hanging around from before I updated the packages. 

Closing the issues since I can't reproduce it either

**Comment by ProductiveRage** [comment]
Quite possibly - I suspect that the analyser update fixed it and either your VS hadn't loaded the new analyser or hadn't realised that it needed to re-run it. It's possible that a rebuild was required and it's possible that you just needed to restart VS (though you should have gotten a warning about this.. maybe it was hidden among all of the other warnings that you still had). Either way, I'm happy that it's fixed now!
