### ISSUE TITLE
The need for CtorSet

### ISSUE THREAD

**Issue by ArtGangsta** [ProductiveRage/Bridge.Immutable#8]
What is the reason for CtorSet?   After modifying your example class slightly, this seems to compile:

```
public class PersonDetails
{
	public PersonDetails(int id, string name, string reportsTo)
	{
		Id = id;
		Name = name;
		ReportsTo = reportsTo;
	}
	public int Id { get; private set; }
	public string Name { get;  private set; }
	public string ReportsTo { get;  private set; }
}
```

I think I'm missing something.  Could explain?

**Comment by ProductiveRage** [comment]
This library is about preventing null values from sneaking into the system as well as making it easy to write immutable classes.

So CtorSet not only sets the property, it also throws if the value is null. So you would need to change the example class to this for parity:

```
public class PersonDetails
{
	public PersonDetails(int id, string name, string reportsTo)
	{
		if (name == null)
			throw new ArgumentNullException(nameof(name));
		if (reportsTo == null)
			throw new ArgumentNullException(nameof(reportsTo));
		Id = id;
		Name = name;
		ReportsTo = reportsTo;
	}
	public int Id { get; private set; }
	public string Name { get;  private set; }
	public string ReportsTo { get;  private set; }
}
```

This sort of code quickly becomes 50% argument-null validation, which I got sick of when I was writing them by hand and so that's mostly what CtorSet is for (it makes the resulting classes more succinct).
