### ISSUE TITLE
Another way to do "With"..

### ISSUE THREAD

**Issue by ArtGangsta** [ProductiveRage/Bridge.Immutable#9]
Rather than have multiple With methods, just have one, with every parameter -- and only accept the ones that are specified by the caller:
```
	public PersonDetails With(int? id = null, string name = null, string reportsTo = null)
	{
		return new PersonDetails( id ?? Id, name ?? Name, reportsTo ?? ReportsTo);
	}
```
Then you can do;

        var newPd = existingPd.With( reportsTo: "Joe Bloke" );

using a named-parameter at the call-site to make it clear what parameter you're trying to set.

**Comment by ProductiveRage** [comment]
This is another approach, yes. These "With" methods would have to be written or generated for every immutable type, though, so are you suggesting that these be written by hand or that the library should auto-generate them somehow?

Your code is a slight oversimplification, though, since the "With" extension method in this library performs an equality comparison on the current and new value and will not generate a new instance if the values match. So your code would have to be something a bit more like:

```
	public PersonDetails With(int? id = null, string name = null, string reportsTo = null)
	{
		if (((id == null) || id.Equals(Id))
		&& ((name == null) || name.Equals(Name))
		&& ((reportsTo == null) || name.Equals(ReportsTo)))
			return this;
		return new PersonDetails( id ?? Id, name ?? Name, reportsTo ?? ReportsTo);
	}
```

If written by hand then this would be something that it would be easy to make copy-paste errors in. If generated by an analyser / code fix in the library then that problem would be avoided but the classes would still be longer and I was hoping to get short class declarations (hence the use of CtorSet, as you asked about in Issue #8).
